/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.CaseParticipant;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "caserequest", description = "the caserequest API")
public interface CaserequestApi {

    @ApiOperation(value = "Get Participants Case Request", nickname = "getParticipantsCaseRequest", notes = "Get Participants Case Request", response = CaseParticipant.class, tags={ "GetParticipantsCaseRequest", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Retrieved participants data based on the given identification", response = CaseParticipant.class),
        @ApiResponse(code = 400, message = "application error"),
        @ApiResponse(code = 404, message = "basic data not found"),
        @ApiResponse(code = 500, message = "business or technical error") })
    @RequestMapping(value = "/caserequest/{id_case-request}/participants/{id_participant}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<CaseParticipant> getParticipantsCaseRequest(@ApiParam(value = "id_case-request",required=true) @PathVariable("id_case-request") String idCaseRequest,@ApiParam(value = "id_participant",required=true) @PathVariable("id_participant") String idParticipant);

}
